import {IDENTITY} from '@dmjone/brand';
import {TERMS_URL,PRIVACY_URL,ENROLLMENT_URL} from '@dmjone/shared';
import type {DocumentEmailMessage} from './provider.js';
const escape=(value:string)=>value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
function link(value:string){if(new URL(value).protocol!=='https:')throw new Error('Document links require HTTPS');return escape(value);}
export const RECORDS_EMAIL='records@dmj.one';
export function recordsCc(to:string):string[]{return to.trim().toLowerCase()===RECORDS_EMAIL?[]:[RECORDS_EMAIL];}
export function messageText(m:DocumentEmailMessage):string{
 const greeting=m.recipientName?'Dear '+m.recipientName+',':'Hello,';
 const title=m.nda?'Your dmj.one offer and NDA are ready. We look forward to learning and building with you.':`Your dmj.one ${m.kind==='upload'?'document':m.kind} is ready.`;
 const next=m.nda?`\n\nPlease complete these steps:\n1. Read the offer and the attached NDA. Sign and date EVERY PAGE of both documents and complete the acceptance fields.\n2. Email both signed copies to contact@dmj.one.\n3. After returning them, enroll at ${ENROLLMENT_URL} to begin.\n4. Complete an accurate timesheet entry for every working day during the engagement.\n\nVerify the original NDA: ${m.nda.downloadUrl}`:'';
 return `${greeting}\n\n${title}\n\nDocument reference: ${m.documentId}\n\nOpen your document:\n${m.downloadUrl}\n\nDownload password:\n${m.downloadPassword}\n\nUse the password above when prompted to download your PDF.${next}\n\nTerms & Conditions: ${TERMS_URL}\nPrivacy Policy: ${PRIVACY_URL}\n\nIf you have any questions, reply to this email or contact contact@dmj.one.\n\nWarm regards,\ndmj.one\n${IDENTITY.motto}\ncontact@dmj.one`;
}
/** Self-contained multipart email styling, with no remote images or tracking resources. */
export function messageHtml(m:DocumentEmailMessage):string{
 const name=m.recipientName?'Dear '+escape(m.recipientName)+',':'Hello,';
 const heading=m.nda?'An invitation to learn and grow.':'Your document is ready.';
 const intro=m.nda?'Your offer letter and non-disclosure agreement are ready for your review. We look forward to learning and building with you.':`Your ${m.kind==='upload'?'document':escape(m.kind)} has been issued by dmj.one and is ready to view, verify and download.`;
 const steps=m.nda?`<tr><td style="padding:0 32px 26px"><h2 style="font-size:19px;color:#2b2a28;margin:0 0 12px">Your next steps</h2><ol style="padding-left:22px;margin:0;color:#514a3c;line-height:1.8"><li>Read the offer and attached NDA. <strong>Sign and date every page of both documents</strong> and complete the acceptance fields.</li><li>Email both signed copies to <a style="color:#876616" href="mailto:contact@dmj.one">contact@dmj.one</a>.</li><li>Then <a style="color:#876616" href="${ENROLLMENT_URL}">enroll at timesheet.dmj.one</a> to begin.</li><li><strong>Complete an accurate timesheet entry every working day</strong> during the engagement.</li></ol><p style="font-size:13px;margin:16px 0 0;color:#675f54">The NDA is attached as a PDF. You can also <a style="color:#876616" href="${link(m.nda.downloadUrl)}">verify the issued NDA online</a>.</p></td></tr>`:'';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#f3efe8;color:#2b2a28;font-family:Georgia,'Times New Roman',serif"><div style="display:none;max-height:0;overflow:hidden">Your document, download password and next steps from dmj.one.</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f3efe8"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:#fffdfb;border:1px solid #cba85e;border-radius:12px"><tr><td style="padding:26px 32px 20px;border-bottom:1px solid #e5d8b8"><a href="https://dmj.one" style="font-size:28px;font-weight:bold;text-decoration:none;color:#876616">dmj.one</a><div style="font:12px/1.5 Arial,sans-serif;letter-spacing:.3px;color:#776b55;margin-top:8px">${escape(IDENTITY.motto)}</div></td></tr><tr><td style="padding:28px 32px 18px"><p style="margin:0 0 16px;font-size:16px">${name}</p><h1 style="font-size:28px;line-height:1.25;color:#876616;margin:0 0 18px">${heading}</h1><p style="font-size:16px;line-height:1.7;margin:0 0 20px">${intro}</p><a href="${link(m.downloadUrl)}" style="display:inline-block;background:#876616;color:#fffdfb;font:bold 14px Arial,sans-serif;text-decoration:none;padding:14px 22px;border-radius:6px">${m.nda?'Open your offer letter':'Open your document'}</a><p style="font:11px Arial,sans-serif;color:#776b55;margin:14px 0 0">Document reference: ${escape(m.documentId)}</p></td></tr><tr><td style="padding:8px 32px 26px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f6f0e2;border:1px solid #e4d5b4;border-radius:7px"><tr><td style="padding:18px"><div style="font:bold 12px Arial,sans-serif;color:#6c5420;margin-bottom:10px">YOUR DOWNLOAD PASSWORD</div><code style="display:block;white-space:pre-wrap;word-break:break-all;font:16px/1.6 Consolas,Monaco,monospace;color:#2b2a28">${escape(m.downloadPassword)}</code><p style="font:12px/1.6 Arial,sans-serif;color:#675f54;margin:10px 0 0">Use this password when prompted to download your PDF.</p></td></tr></table></td></tr>${steps}<tr><td style="padding:0 32px 28px;font-size:15px;line-height:1.7"><p style="margin:0 0 16px">If anything needs clarification, reply to this email. We are happy to help.</p><p style="margin:0">Warm regards,<br><strong>dmj.one</strong><br><a style="color:#876616" href="mailto:contact@dmj.one">contact@dmj.one</a></p></td></tr><tr><td style="padding:18px 32px;border-top:1px solid #e5d8b8;font:11px/1.7 Arial,sans-serif;color:#776b55"><a style="color:#876616" href="${TERMS_URL}">Terms &amp; Conditions</a> &nbsp;|&nbsp; <a style="color:#876616" href="${PRIVACY_URL}">Privacy Policy</a><br>This email contains private access details for your document.</td></tr></table></td></tr></table></body></html>`;
}
